version: "2"
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  sonar-java:
    enabled: true
    channel: sonar-java5-14
    config:
      sonar.java.source: "8"
exclude_patterns:
  - .mvn/
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/"

